name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ref-interpreter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
      - run: opam install ocamlbuild
      - run: cd interpreter && opam exec make all

  build-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build JS API
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1
        with:
          source: "document/js-api/index.bs"
          destination: "document/js-api/index.html"

      - run: pip install bikeshed && bikeshed update
      - run: pip install six
      - run: sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - run: pip install sphinx
      - run: cd document/core && make all

      - name: Publish HTML to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./document
          github_token: ${{ secrets.GITHUB_TOKEN }}
